sudo: false

language: node_js

node_js:
  - 6
  - 7

before_install:
  - npm install -g yarn@latest

script:
  - yarn run ci

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: D6wA+nuZeIXz7Y76uCBJl9h89rIEpwUkfroMKMX9vkX35C/CebeS7fYQ9A6BHVW0MgLHYpDHfBQDP4h74nD/ZQWNpsM6xyIXVPDouufdRNAbeJnrv1bwz9WgQH8wCPU0/P9/SwmxGGSz62acbYRVYUhpucGl0MsK/AK2g/NK+JKhn0UEPKsfXR/gBx/a75pb0daUgKjHldEhIA0Ts8D01nRwf43uMJWmfLZSVIDbxfA0sfWMOpZjdK8lqefq28yHgMtkAgmG0lj1nyvkujukC0V7hoNvYNOq/ktDc/Cv/9DhGWAKM+HdTQjmv+0ZH0oxl/PSB7La/Ptfa0Q5P1/r1jCohJiwT0la7r0vuXIoVqcNCY/jU+MNZHkmaSIITrGzU7YxWvbTecRdQEE5sdtCF/rX8p6oMj1P7u1zdAhs6b40EzcgPESmnw9GtFcYDHi5vSc+7nV8jRDU3WRq/YH1eA3m378Q5OEHb4XP8bMI6rsEV2Nv1vn0zlXIpdJ++0VFoee9fakvsZgNzjDkhmFwwIfJ2kjbTPiY7i0AYfGOx1CKv8MMhw6VkPYbBdQKXDz1WkWr/54Sa1MCAWxnLhqgM+gqvCiecNxWnMCvsjEY0aOA5CGRLKpw81ISc1sjUzNCA3hoG6zorPDwmnH+/uC/n4AnD0JVGKdQLp6rOiLXbG0=
